title:             Meiras Blog 2025
email:             contas4u@gmail.com
description:       A Blog Theme by Mig T.
author:            MIg T. (forked from Bootstrap-Clean Blog-Jekyll)
baseurl:           "/Meiras-Blog-Bootstrap/"
url:               "https://linuxfce.github.io/Meiras-Blog-Bootstrap/"

# Social Profiles
# twitter_username:  luis_linuxfce
github_username:   linuxfce
# facebook_username: Miguel
# linkedin_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
