title:             Meiras Blog 2018
email:             meiras.contact@gmail.com
description:       A Blog Theme by L. Mig. T.
author:            Meiras (fork from Bootstrap)
baseurl:           "/Meiras-Blog-Bootstrap/"
url:               "https://linuxfce.github.io/Meiras-Blog-Bootstrap/"

# Social Profiles
twitter_username:  @luis_linuxfce
github_username:   linuxfce
# facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
